FROM node:14.16.0
LABEL maintainer="Jose Francisco Alvarez Valdez<alvaresvaldes89@gmail.com>"
# RUN (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh
# ARG DOPPLER_TOKEN
# ENV DOPPLER_TOKEN=$DOPPLER_TOKEN
# RUN doppler setup --token=$DOPPLER_TOKEN -c loc
# ENV TZ="America/Chicago"
# RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
USER root
RUN apt update && apt install nano -y
RUN mkdir -p /home/node/app/src
# RUN mkdir /home/node/app/tmp
WORKDIR /home/node/app
RUN mkdir node_modules && chown -R root:root /home/node/app
#USER node
COPY package*.json ./
COPY src/server.js src
RUN npm install
EXPOSE 3002
#USER root
RUN npm install -g nodemon mocha
CMD ["nodemon", "src/server.js"]