FROM node:14.16.0
LABEL maintainer="Jose Francisco Alvarez Valdez<alvaresvaldes89@gmail.com>"
ENV TZ="America/Monterrey"
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
RUN mkdir node_modules && chown -R node:node /home/node/app
COPY package*.json ./
COPY . .
RUN npm install
RUN npm install -g nodemon mocha
USER root
CMD ["nodemon", "src/server.js"]