version: '3.8'
services:
    #Databases
    mongo-db-ixaya:
        image: mongo:4.1.8-xenial
        container_name: mongo-db-ixaya
        restart: unless-stopped
        environment:
        - MONGO_INITDB_DATABASE=ixaya
        networks:
        - ixaya
        ports:
        - "27018:27017"

    #Api gateway
    api-ixaya:
        image: jalvarez/ixaya-api-gateway:local
        container_name: ixaya-api-gateway
        restart: unless-stopped
        environment:
        - API_KEY=1
        - PORT=3000
        ports:
        - '4000:3000'
        - '9242:9229'
        volumes:
        - ./api-gateway/src/:/home/node/app/src
        build:
          context: ./api-gateway
          dockerfile: ./Dockerfile.dev
        networks:
        - ixaya

    #Microservices
    orders:
        image: jalvarez/ixaya-orders:local
        container_name: ixaya-orders
        restart: unless-stopped
        environment:
        - MONGO_DB_HOST=mongo-db-ixaya
        - MONGO_DB_NAME=ixaya
        volumes:
        - ./orders/src:/home/node/app/src
        depends_on:
        - api-ixaya
        - mongo-db-ixaya
        build:
          context: ./orders
          dockerfile: ./Dockerfile.dev
        networks:
        - ixaya

    products:
        image: jalvarez/ixaya-proucts:local
        container_name: ixaya-products
        restart: unless-stopped
        environment:
        - MONGO_DB_HOST=mongo-db-ixaya
        - MONGO_DB_NAME=ixaya
        volumes:
        - ./products/src:/home/node/app/src
        depends_on:
        - api-ixaya
        - mongo-db-ixaya
        build:
          context: ./products
          dockerfile: ./Dockerfile.dev
        networks:
        - ixaya

    users:
        image: jalvarez/ixaya-users:local
        container_name: ixaya-users
        restart: unless-stopped
        environment:
        - MONGO_DB_HOST=mongo-db-ixaya
        - MONGO_DB_NAME=ixaya
        - JWT_PASSWORD=fdjan8329cb"53
        # - MONGO_DB_USER=jalvarez
        # - MONGO_DB_PASSWORD=WT8j596KaSYBKR3L
        # ports:
        # - '4002:3002'
        volumes:
        - ./users/src:/home/node/app/src
        depends_on:
        - api-ixaya
        - mongo-db-ixaya
        build:
          context: ./users
          dockerfile: ./Dockerfile.dev
        networks:
        - ixaya

networks:
    ixaya:
        driver: bridge
